#!/usr/bin/env bash
if [[ $DEBUG != "" ]]; then
  set -x
fi

GIT_ROOT="$(git rev-parse --show-toplevel)"
OLDPWD="$PWD"

if [[ "$PWD" != "$GIT_ROOT" ]]; then
  echo "going to GIT_ROOT to avoid errors on octodns-sync and friends"
  # shellcheck disable=SC2164
  cd "$GIT_ROOT"
fi

if [ -z "${CI}" ]; then
  dotenvx run -f .env -- deno run -A "$GIT_ROOT/utils/dns-records.ts" "$@"
else
  dotenvx run -f .env.ci -- deno run -A "$GIT_ROOT/utils/dns-records.ts" "$@"
fi

# shellcheck disable=SC2164
cd "$OLDPWD"